server {
    listen 80;
    listen [::]:80;
    server_name {HOST};

    root /var/www/{HOST}/html;

    access_log /var/log/nginx/{HOST}.80.access.log;
    error_log  /var/log/nginx/{HOST}.80.error.log;

    location ^~ /.well-known/acme-challenge/ {
        try_files $uri =404;
        default_type "text/plain";
        allow all;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}